/*
 *  This file is part of CoCalc: Copyright © 2026 Sagemath, Inc.
 *  License: MS-RSL – see LICENSE.md for details
 */

export function parsePathWithOptionalLineSuffix(path: string): {
  path: string;
  line?: number;
} {
  const trimmed = path.trim();
  // Parse from the last :line(:col) suffix and allow punctuation commonly
  // attached to paths in prose generated by agents.
  const match =
    trimmed.match(/^(.*):(\d+):\d+(?:[)\].,;!?'"`]+)?$/) ??
    trimmed.match(/^(.*):(\d+)(?:[)\].,;!?'"`]+)?$/);
  if (!match) return { path: trimmed };
  const candidatePath = match[1].trim();
  if (!candidatePath || candidatePath.endsWith("/")) {
    return { path: trimmed };
  }
  const line = Number(match[2]);
  if (!Number.isFinite(line) || line <= 0) {
    return { path: trimmed };
  }
  return { path: candidatePath, line };
}

export function parseLineFromHashFragment(hash?: string): number | undefined {
  if (!hash) return undefined;
  const cleaned = hash.startsWith("#") ? hash.slice(1) : hash;
  const match = cleaned.match(/^L(\d+)(?:C\d+)?(?:-L?\d+)?$/i);
  if (!match) return undefined;
  const line = Number(match[1]);
  return Number.isFinite(line) && line > 0 ? line : undefined;
}
