/*
 *  This file is part of CoCalc: Copyright (c) 2026 Sagemath, Inc.
 *  License: MS-RSL - see LICENSE.md for details
 */

import getLogger from "@cocalc/backend/logger";
import type { Client } from "@cocalc/database/pool";
import type { PgTableConstraint } from "@cocalc/util/db-schema";
import { postgresIdentifierName, quoteIdentifier } from "./index-metadata";
import type { DBSchema, TableSchema } from "./types";

const log = getLogger("db:schema:constraints");

type CurrentConstraint = {
  name: string;
  type: "c" | "f" | "u";
  validated: boolean;
  columns: string[];
  expression: string | null;
  referenced_table: string | null;
  referenced_columns: string[];
  on_delete: string;
  on_update: string;
};

type CurrentConstraintRow = Omit<
  CurrentConstraint,
  "columns" | "referenced_columns"
> & {
  columns: string[] | string | null;
  referenced_columns: string[] | string | null;
};

export type ConstraintAction =
  | { action: "add"; constraint: PgTableConstraint }
  | { action: "validate"; name: string }
  | {
      action: "conflict";
      constraint: PgTableConstraint;
      current: CurrentConstraint;
    };

const ACTION_CODES: Record<string, string> = {
  a: "no action",
  r: "restrict",
  c: "cascade",
  n: "set null",
  d: "set default",
};

function sameColumns(left: string[], right: string[]): boolean {
  return (
    left.length === right.length &&
    left.every((column, index) => column === right[index])
  );
}

function postgresTextArray(value: string[] | string | null): string[] {
  if (Array.isArray(value)) return value;
  if (value == null || value === "{}") return [];
  if (!value.startsWith("{") || !value.endsWith("}")) {
    throw new Error(`invalid PostgreSQL text array: ${value}`);
  }
  // Constraint column names are identifiers generated by PostgreSQL and do
  // not contain commas. Handle quoted identifier escapes defensively anyway.
  return value
    .slice(1, -1)
    .split(",")
    .map((item) => item.replace(/^"|"$/g, "").replace(/\\"/g, '"'));
}

function normalizeCheck(expression: string | null): string {
  let value = (expression ?? "").trim().toLowerCase();
  while (value.startsWith("(") && value.endsWith(")")) {
    value = value.slice(1, -1).trim();
  }
  return value.replace(/\s+/g, " ");
}

function equivalent(
  desired: PgTableConstraint,
  current: CurrentConstraint,
): boolean {
  if (desired.type === "check") {
    return (
      current.type === "c" &&
      normalizeCheck(current.expression) === normalizeCheck(desired.expression)
    );
  }
  if (desired.type === "unique") {
    return (
      current.type === "u" && sameColumns(current.columns, desired.columns)
    );
  }
  return (
    current.type === "f" &&
    sameColumns(current.columns, desired.columns) &&
    current.referenced_table === desired.references.table &&
    sameColumns(current.referenced_columns, desired.references.columns) &&
    ACTION_CODES[current.on_delete] === (desired.on_delete ?? "no action") &&
    ACTION_CODES[current.on_update] === (desired.on_update ?? "no action")
  );
}

async function getCurrentConstraints(
  db: Client,
  table: string,
): Promise<CurrentConstraint[]> {
  const { rows } = await db.query(
    `SELECT constraint_row.conname AS name,
            constraint_row.contype AS type,
            constraint_row.convalidated AS validated,
            ARRAY(
              SELECT attribute.attname
                FROM unnest(constraint_row.conkey)
                  WITH ORDINALITY AS key(attnum, ordinality)
                JOIN pg_attribute AS attribute
                  ON attribute.attrelid=constraint_row.conrelid
                 AND attribute.attnum=key.attnum
               ORDER BY key.ordinality
            ) AS columns,
            pg_get_expr(
              constraint_row.conbin,
              constraint_row.conrelid,
              false
            ) AS expression,
            referenced_table.relname AS referenced_table,
            ARRAY(
              SELECT attribute.attname
                FROM unnest(constraint_row.confkey)
                  WITH ORDINALITY AS key(attnum, ordinality)
                JOIN pg_attribute AS attribute
                  ON attribute.attrelid=constraint_row.confrelid
                 AND attribute.attnum=key.attnum
               ORDER BY key.ordinality
            ) AS referenced_columns,
            constraint_row.confdeltype AS on_delete,
            constraint_row.confupdtype AS on_update
       FROM pg_constraint AS constraint_row
       LEFT JOIN pg_class AS referenced_table
         ON referenced_table.oid=constraint_row.confrelid
      WHERE constraint_row.conrelid=to_regclass($1)
        AND constraint_row.contype IN ('c','f','u')`,
    [table],
  );
  return (rows as CurrentConstraintRow[]).map((row) => ({
    ...row,
    columns: postgresTextArray(row.columns),
    referenced_columns: postgresTextArray(row.referenced_columns),
  }));
}

export async function getConstraintActions(
  db: Client,
  schema: TableSchema,
): Promise<ConstraintAction[]> {
  const desired = schema.pg_constraints ?? [];
  if (desired.length === 0) return [];
  const current = await getCurrentConstraints(db, schema.name);
  const actions: ConstraintAction[] = [];
  for (const constraint of desired) {
    const sameName = current.find(
      ({ name }) => name === postgresIdentifierName(constraint.name),
    );
    // PostgreSQL rewrites check expressions while storing them (for example,
    // IN becomes = ANY with explicit casts). The stable, source-controlled
    // constraint name is therefore the identity for checks.
    if (constraint.type === "check" && sameName?.type === "c") {
      if (!sameName.validated) {
        actions.push({ action: "validate", name: sameName.name });
      }
      continue;
    }
    const matching = current.find((item) => equivalent(constraint, item));
    if (matching != null) {
      if (!matching.validated) {
        actions.push({ action: "validate", name: matching.name });
      }
      continue;
    }
    if (sameName != null) {
      actions.push({ action: "conflict", constraint, current: sameName });
    } else {
      actions.push({ action: "add", constraint });
    }
  }
  return actions;
}

function constraintSql(constraint: PgTableConstraint): string {
  if (constraint.type === "check") {
    return `CHECK (${constraint.expression})`;
  }
  const columns = constraint.columns.map(quoteIdentifier).join(", ");
  if (constraint.type === "unique") {
    return `UNIQUE (${columns})`;
  }
  const referencedColumns = constraint.references.columns
    .map(quoteIdentifier)
    .join(", ");
  const onDelete = constraint.on_delete
    ? ` ON DELETE ${constraint.on_delete.toUpperCase()}`
    : "";
  const onUpdate = constraint.on_update
    ? ` ON UPDATE ${constraint.on_update.toUpperCase()}`
    : "";
  return `FOREIGN KEY (${columns}) REFERENCES ${quoteIdentifier(
    constraint.references.table,
  )} (${referencedColumns})${onDelete}${onUpdate}`;
}

export async function syncTableSchemaConstraints(
  db: Client,
  schema: TableSchema,
): Promise<void> {
  const actions = await getConstraintActions(db, schema);
  if (actions.length === 0) return;
  log.info("converging table constraints", { table: schema.name, actions });
  for (const action of actions) {
    if (action.action === "conflict") {
      throw new Error(
        `constraint ${action.constraint.name} on ${schema.name} has an unexpected definition`,
      );
    }
    if (action.action === "validate") {
      await db.query(
        `ALTER TABLE ${quoteIdentifier(
          schema.name,
        )} VALIDATE CONSTRAINT ${quoteIdentifier(action.name)}`,
      );
      continue;
    }
    await db.query(
      `ALTER TABLE ${quoteIdentifier(schema.name)} ADD CONSTRAINT ${quoteIdentifier(
        postgresIdentifierName(action.constraint.name),
      )} ${constraintSql(action.constraint)}`,
    );
  }
}

export async function syncSchemaConstraints(
  db: Client,
  dbSchema: DBSchema,
): Promise<void> {
  for (const schema of Object.values(dbSchema)) {
    if (schema.virtual || schema.external) continue;
    await syncTableSchemaConstraints(db, schema);
  }
}

export async function schemaConstraintsNeedSync(
  db: Client,
  dbSchema: DBSchema,
): Promise<boolean> {
  for (const schema of Object.values(dbSchema)) {
    if (schema.virtual || schema.external) continue;
    if ((await getConstraintActions(db, schema)).length > 0) return true;
  }
  return false;
}
